# Generated by Django 3.2.8 on 2021-12-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_name', models.CharField(max_length=30)),
                ('poke_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=20)),
            ],
        ),
    ]
